<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jose Saavedra UCSB Spring 2025">

<title>Predicting the NBA MVP</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="NBA_MVP_files/libs/clipboard/clipboard.min.js"></script>
<script src="NBA_MVP_files/libs/quarto-html/quarto.js"></script>
<script src="NBA_MVP_files/libs/quarto-html/popper.min.js"></script>
<script src="NBA_MVP_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="NBA_MVP_files/libs/quarto-html/anchor.min.js"></script>
<link href="NBA_MVP_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="NBA_MVP_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="NBA_MVP_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="NBA_MVP_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="NBA_MVP_files/libs/bootstrap/bootstrap-10daa034703793678e481cc8cee6d76f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sections</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation">Motivation</a></li>
  <li><a href="#roadmap" id="toc-roadmap" class="nav-link" data-scroll-target="#roadmap">Roadmap</a></li>
  </ul></li>
  <li><a href="#data-set" id="toc-data-set" class="nav-link" data-scroll-target="#data-set">Data Set</a>
  <ul class="collapse">
  <li><a href="#loading-necessary-packages-and-data-set" id="toc-loading-necessary-packages-and-data-set" class="nav-link" data-scroll-target="#loading-necessary-packages-and-data-set">Loading Necessary Packages and Data Set</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a></li>
  <li><a href="#variable-correlation-plot" id="toc-variable-correlation-plot" class="nav-link" data-scroll-target="#variable-correlation-plot">Variable Correlation Plot</a></li>
  <li><a href="#visual-eda" id="toc-visual-eda" class="nav-link" data-scroll-target="#visual-eda">Visual EDA</a></li>
  </ul></li>
  <li><a href="#building-the-models" id="toc-building-the-models" class="nav-link" data-scroll-target="#building-the-models">Building the Models</a>
  <ul class="collapse">
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection">Model Selection</a></li>
  <li><a href="#splitting-the-data" id="toc-splitting-the-data" class="nav-link" data-scroll-target="#splitting-the-data">Splitting the Data</a></li>
  <li><a href="#recipe-building" id="toc-recipe-building" class="nav-link" data-scroll-target="#recipe-building">Recipe Building</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a></li>
  <li><a href="#results-for-best-model" id="toc-results-for-best-model" class="nav-link" data-scroll-target="#results-for-best-model">Results for Best Model</a></li>
  <li><a href="#fitting-best-model-to-training-data" id="toc-fitting-best-model-to-training-data" class="nav-link" data-scroll-target="#fitting-best-model-to-training-data">Fitting best model to training data</a></li>
  </ul></li>
  <li><a href="#predicting-the-2025-nba-mvp" id="toc-predicting-the-2025-nba-mvp" class="nav-link" data-scroll-target="#predicting-the-2025-nba-mvp">Predicting the 2025 NBA MVP</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#sources" id="toc-sources" class="nav-link" data-scroll-target="#sources">Sources</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting the NBA MVP</h1>
<p class="subtitle lead">Using Machine Learning Models to Predict NBA MVP Voting</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jose Saavedra<br>
UCSB Spring 2025 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="nba-logo-png_seeklogo-247736.png" class="quarto-figure quarto-figure-center figure-img" width="302" height="251"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tumblr_mme7xacNUT1qk5jr2o1_500.webp" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This project aims to build a machine learning model that can predict what player is most probable to win the MVP award in any given season using game performance metrics such as points per game, assists per game, rebounds per game, etc. The data set I will be using is a data set containing Player MVP voting data from the 1982-2022 NBA season. This data set includes player information for each season such as player name and team, performance metrics, and award share earned by a player in that season’s MVP voting.</p>
<section id="motivation" class="level3">
<h3 class="anchored" data-anchor-id="motivation">Motivation</h3>
<p>The NBA has had a rich history of great players who have forever changed the game and left a lasting legacy still felt by many in the league today. These players are oftent times recognized for their skill and talent through the NBA’s MVP award. Players compete all season for the chance to hoist the trophy at the end of the season, and many players do show out and in those years the MVP race can be very close. As the season progresses different players rotate in and out of MVP talks and the one player who voters deem to be consistently the best throughout the season will ultimately lift up the MVP trophy in February.</p>
<p>Being as basketball is now more than ever an entertainment industry, the NBA MVP award has seen some controversy in the last couple of years. Fans use terms like “voter fatigue” to describe how a player who has won the award multiple in time in the previous seasons may be at risk of losing their deserved trophy due to voters wanting to create new story lines for the market. Other things also affect voters choices, things such as a player ’s behavior, player story lines, team story lines, suspensions, controversies, are to name a few. We’ve all heard the saying “ball don’t lie” and that is the ultimate motivation for this project. I want to cut out the story lines, the voter fatigue, and anything else that would influence a voters choice and look at the raw stats to see if we can predict who was statistically, the most valuable player of the season.</p>
</section>
<section id="roadmap" class="level3">
<h3 class="anchored" data-anchor-id="roadmap">Roadmap</h3>
<p>We will first begin identifying all features of our data set. This includes things like the structure of the data, variables in the data set which we can use for modeling, and checking for any potential missing values. We will also try to reduce the overall size of our data set to help our models train faster and more efficiently. Next we will perform EDA on the data set using graphs and plots such as correlation plots, box plots, and scatter plots to try and identify any significant relationships in the data that may help us in our model fitting. After this we will finalize our formula using model selection and begin to fit our models to training data using the tidymodels package. In this project our goal is to predict the outcome variable award_share, which is continuous, the player with the highest award_share value for the respective season gets the MVP award. After fitting multiple models to the training data we will then assess each models performance and choose the best performing model to then be used on our testing data set to see how well our model generalizes on unseen data. Lastly we will assess our chosen model’s performance using various metrics and draw conclusions from our findings and put our model to the test using the newly available 2025 NBA season player data set.</p>
</section>
</section>
<section id="data-set" class="level2">
<h2 class="anchored" data-anchor-id="data-set">Data Set</h2>
<section id="loading-necessary-packages-and-data-set" class="level3">
<h3 class="anchored" data-anchor-id="loading-necessary-packages-and-data-set">Loading Necessary Packages and Data Set</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Required packages and nba data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(paletteer)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ranger)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xgboost)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vip)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># clearing global enviroment </span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>nba <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'/Users/paris/SPRING 25/PSTAT 131/PROJECT/NBA_Dataset.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The previously mentioned <a href="https://www.kaggle.com/datasets/robertsunderhaft/nba-player-season-statistics-with-mvp-win-share/data">data set</a> was provided by user Robert Sunderhaft via Kaggle</p>
<p>Now I don’t really have that much space in this document and we have 55 variables to work with (see attached codebook) . Given that I have good knowledge in both the NBA and in statistics I chose to remove a good amount of the variables in this data set. There are a lot of variables that are direct results from others, such as orb_per_g and drb_per_g (offensive and defensive rebounds per game) would both make up the trb_per_g (rebounds per game) variable. Player position and age are also not included as these are have no effect on MVP voting. The following list is of all the variables I have chosen to be relevant to this analysis. Later on I will do model selection to finalize this list of variables to be used in fitting the model.</p>
<ul>
<li><p><strong>season:</strong> indicates the basketball season of play. 1982 would mean the 1981-1982 basketball season</p></li>
<li><p><strong>player:</strong> name of player</p></li>
<li><p><strong>g:</strong> games played</p></li>
<li><p><strong>gs:</strong> games started</p></li>
<li><p><strong>mp_per_g:</strong> minutes per game</p></li>
<li><p><strong>fg_per_g:</strong> field goals per game</p></li>
<li><p><strong>fga_per_g:</strong> field goals attempted per game</p></li>
<li><p><strong>fg_pct:</strong> field goal percentage per game</p></li>
<li><p><strong>efg_pct:</strong> effective shooting percentage per game</p></li>
<li><p><strong>ft_per_g:</strong> free throws per game</p></li>
<li><p><strong>fta_per_g:</strong> free throws attempted per game</p></li>
<li><p><strong>ft_pct:</strong> free throw percentage per game</p></li>
<li><p><strong>trb_per_g:</strong> total rebounds per game</p></li>
<li><p><strong>ast_per_g:</strong> assists per game</p></li>
<li><p><strong>stl_per_g:</strong> steals per game</p></li>
<li><p><strong>blk_per_g:</strong> blocks per game</p></li>
<li><p><strong>tov_per_g:</strong> turnovers per game</p></li>
<li><p><strong>pts_per_g:</strong> points per game</p></li>
<li><p><strong>mp:</strong> minutes played total</p></li>
<li><p><strong>per:</strong> player efficiency rating</p></li>
<li><p><strong>ts_pct:</strong> true shooting percentage</p></li>
<li><p><strong>usg_pct:</strong> usage percentage</p></li>
<li><p><strong>ows:</strong> offensive win shares</p></li>
<li><p><strong>dws:</strong> defensive win shares</p></li>
<li><p><strong>ws:</strong> win shares</p></li>
<li><p><strong>ws_per_48:</strong> win shares per 48 games</p></li>
<li><p><strong>vorp:</strong> value over replacement</p></li>
<li><p><strong>award_share:</strong> MVP voting win share percentage</p></li>
<li><p><strong>mov:</strong> average margin of victory during the season</p></li>
<li><p><strong>mov_adj:</strong> average Margin of Victory adjusted for difficulty of opponent during season</p></li>
<li><p><strong>win_loss_pct:</strong> player’s win loss percentage for the season</p></li>
<li><p><strong>bpm:</strong> box plus minus</p></li>
</ul>
<p>The list of variables to use is now 32, which is still a lot. I aim to identify which variables are the biggest indicators for potential MVP voting in the next section.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># selecting relevant variables</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>nba <span class="ot">&lt;-</span> nba <span class="sc">%&gt;%</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(season, player, g, gs, fg_per_g, fga_per_g, fg_pct, efg_pct, ft_per_g, fta_per_g, ft_pct, trb_per_g, ast_per_g, stl_per_g, blk_per_g, tov_per_g, pts_per_g, mp, mp_per_g, per, ts_pct, usg_pct, ows, dws, ws, ws_per_48, vorp, award_share, mov, mov_adj, win_loss_pct, bpm)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># making season a factor variable</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>nba<span class="sc">$</span>season <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(nba<span class="sc">$</span>season)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># checking to see that all variables are captured</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(nba)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32</code></pre>
</div>
</div>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<p>Before we begin predicting who will be the MVP, we need to do some EDA on the data. This will help us first by identifying any potential problems in our data like missing values, variables that need to be made factors before fitting a model, etc. EDA will also help us to identify trends in the data that may be useful in later model selection. Since we are predicting award share (which is a continuous variable), we are doing regression, but for later metrics i will be adding a variable to the data named “is_MVP” which will be a boolean value that is true when the player has the highest value for award_share in the respective season. Also to help us with visualizing the data later, I decided to add a column for players who received at least one vote.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># adding is_MVP variable to the nba data set </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>nba <span class="ot">&lt;-</span> nba <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(season) <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">is_mvp =</span> award_share <span class="sc">==</span> <span class="fu">max</span>(award_share, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mvp_vote =</span> award_share <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># value should be 41 represting the 41 players who earned the award </span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(nba<span class="sc">$</span>is_mvp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 41</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># histogram of is_mvp variable</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nba, <span class="fu">aes</span>(<span class="at">x =</span> is_mvp)) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"gold"</span>)) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="NBA_MVP_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now we see that in total only 41 players out of the over 17697 in the data set were MVP, some of them multiple times. Now 17697 is a lot of players. This data set includes players who may have played only 10 minutes in one season, or maybe even didn’t get on the court once. We next do some data cleaning to reduce the total number of observations and remove observations that would otherwise be beneficial in our model fitting. I will provide accompanying justifications for removing the observations as well.</p>
<p>Since this is not a classification problem, we do not need to worry too much about possible class imbalances.</p>
<section id="data-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning">Data Cleaning</h3>
<p>Now let’s consider the fact that most players who would be considered for the MVP will be players who played a significant amount of minutes in their MVP caliber season. This means that most players who played little to no minutes will have almost no consideration for the award. We explore this more with this graph below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>nba <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(mvp_vote <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mp)) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">100</span>, <span class="at">fill =</span> <span class="st">"gold"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Minutes Played by Players Who Received at Least One MVP Vote"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Minutes Played"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span> </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="NBA_MVP_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>These graphs shows the distribution for player who received at least one vote in their seasons MVP race, with frequency count on the y-axis, and the total minutes played on the x-axis.</p>
<p>We see that in general to be even considered you have to play more than 1500 minutes. We see some outliers in this data and should investigate them further.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>nba <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(player, season, mp, award_share) <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(award_share <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mp, <span class="at">descending =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">player</th>
<th style="text-align: left;">season</th>
<th style="text-align: right;">mp</th>
<th style="text-align: right;">award_share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Michael Jordan</td>
<td style="text-align: left;">1995</td>
<td style="text-align: right;">668</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="even">
<td style="text-align: left;">Magic Johnson</td>
<td style="text-align: left;">1996</td>
<td style="text-align: right;">958</td>
<td style="text-align: right;">0.007</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shaquille O’Neal</td>
<td style="text-align: left;">2007</td>
<td style="text-align: right;">1135</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: left;">Derrick Rose</td>
<td style="text-align: left;">2021</td>
<td style="text-align: right;">1279</td>
<td style="text-align: right;">0.010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Steve Smith</td>
<td style="text-align: left;">1999</td>
<td style="text-align: right;">1314</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arvydas Sabonis</td>
<td style="text-align: left;">1999</td>
<td style="text-align: right;">1349</td>
<td style="text-align: right;">0.003</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now we see two very interesting observations, those of Micheal Jordan in 1995, and Magic Johnson in 1996. These two observations are actually similar as for both players, these were the seasons in which they had returned from a hiatus from basketball. Micheal Jordan had left to play baseball, and Magic Johnson has returned from a hiatus after being diagnosed with AIDs. Now these observations unfortunately will not help our data and could even potentially effect our models performance given their outlier status, my feeling is that these votes were given to them partly due to their name and their story line. For this reason I chose to remove these two from the model. As for the rest of the observations I will introduce a cutoff for minutes played. I choose this value to be 3 standard deviations away from the mean minutes played by players who received an MVP vote. Let’s call Giannis Antetokounmpo for some help.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="bad-data-data-quality.gif" class="img-fluid quarto-figure quarto-figure-center figure-img" width="332"></p>
</figure>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>nba <span class="ot">&lt;-</span> nba <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(mp <span class="sc">&gt;</span> <span class="fu">mean</span>(mp[award_share <span class="sc">&gt;</span> <span class="dv">0</span>]) <span class="sc">-</span> <span class="dv">3</span><span class="sc">*</span><span class="fu">sd</span>(mp[award_share <span class="sc">&gt;</span> <span class="dv">0</span>]))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(nba) <span class="sc">%&gt;%</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">7794</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Nice block Giannis! We now reduced our data by a significant amount. Now let’s take care of the any potential missing values in our data.</p>
<section id="missing-values" class="level4">
<h4 class="anchored" data-anchor-id="missing-values">Missing Values</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vis_miss</span>(nba)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="NBA_MVP_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This is great news! We have no missing values and do not have to worry about filling anything in. Let’s move on to visual EDA</p>
</section>
</section>
<section id="variable-correlation-plot" class="level3">
<h3 class="anchored" data-anchor-id="variable-correlation-plot">Variable Correlation Plot</h3>
<p>We use a correlation matrix to try and identify any variables that have strong correlation with our outcome variable. We can also use this to identify variables that may have strong correlation with each other which I do expect to happen as many of the variables are direct results from others.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>nba_numeric <span class="ot">&lt;-</span> nba <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_if</span>(is.numeric)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(nba_numeric) <span class="sc">%&gt;%</span> </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">corrplot</span>(<span class="at">type =</span> <span class="st">"lower"</span>, <span class="at">method =</span> <span class="st">"pie"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="NBA_MVP_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now this is hard to read but don’t worry, since we are mostly interested in the award_share variable we can make a table for the it’s correlation with all other numeric variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>corr <span class="ot">&lt;-</span> <span class="fu">cor</span>(nba_numeric)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>corr[,<span class="st">"award_share"</span>] <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">g</td>
<td style="text-align: right;">0.0430856</td>
</tr>
<tr class="even">
<td style="text-align: left;">gs</td>
<td style="text-align: right;">0.1435014</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fg_per_g</td>
<td style="text-align: right;">0.3388083</td>
</tr>
<tr class="even">
<td style="text-align: left;">fga_per_g</td>
<td style="text-align: right;">0.2971008</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fg_pct</td>
<td style="text-align: right;">0.1218942</td>
</tr>
<tr class="even">
<td style="text-align: left;">efg_pct</td>
<td style="text-align: right;">0.1122703</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ft_per_g</td>
<td style="text-align: right;">0.3632859</td>
</tr>
<tr class="even">
<td style="text-align: left;">fta_per_g</td>
<td style="text-align: right;">0.3668066</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ft_pct</td>
<td style="text-align: right;">0.0480116</td>
</tr>
<tr class="even">
<td style="text-align: left;">trb_per_g</td>
<td style="text-align: right;">0.1984908</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ast_per_g</td>
<td style="text-align: right;">0.1978637</td>
</tr>
<tr class="even">
<td style="text-align: left;">stl_per_g</td>
<td style="text-align: right;">0.1869070</td>
</tr>
<tr class="odd">
<td style="text-align: left;">blk_per_g</td>
<td style="text-align: right;">0.1412835</td>
</tr>
<tr class="even">
<td style="text-align: left;">tov_per_g</td>
<td style="text-align: right;">0.2694247</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pts_per_g</td>
<td style="text-align: right;">0.3582367</td>
</tr>
<tr class="even">
<td style="text-align: left;">mp</td>
<td style="text-align: right;">0.2102810</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mp_per_g</td>
<td style="text-align: right;">0.2077056</td>
</tr>
<tr class="even">
<td style="text-align: left;">per</td>
<td style="text-align: right;">0.4257460</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ts_pct</td>
<td style="text-align: right;">0.1650090</td>
</tr>
<tr class="even">
<td style="text-align: left;">usg_pct</td>
<td style="text-align: right;">0.2957327</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ows</td>
<td style="text-align: right;">0.4262794</td>
</tr>
<tr class="even">
<td style="text-align: left;">dws</td>
<td style="text-align: right;">0.3073428</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ws</td>
<td style="text-align: right;">0.4565955</td>
</tr>
<tr class="even">
<td style="text-align: left;">ws_per_48</td>
<td style="text-align: right;">0.3902744</td>
</tr>
<tr class="odd">
<td style="text-align: left;">vorp</td>
<td style="text-align: right;">0.5037225</td>
</tr>
<tr class="even">
<td style="text-align: left;">award_share</td>
<td style="text-align: right;">1.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mov</td>
<td style="text-align: right;">0.1860670</td>
</tr>
<tr class="even">
<td style="text-align: left;">mov_adj</td>
<td style="text-align: right;">0.1861582</td>
</tr>
<tr class="odd">
<td style="text-align: left;">win_loss_pct</td>
<td style="text-align: right;">0.1945276</td>
</tr>
<tr class="even">
<td style="text-align: left;">bpm</td>
<td style="text-align: right;">0.4375412</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>In general the more a player has started games the higher their potential MVP voting share is. This is to say that most MVP caliber players are part of the starting lineup on their respective team. Next we see that among all in-game performance metrics, field goals per game was the most correlated with award_share, the rest of them (points, assists, rebounds, etc.) are correlated but not too highly, still I choose to keep them in the model. Variables that are the most correlated with award_share are those which are measurements of a players total value to a team. Notably the variables for win shares and player efficiency. Win shares are estimates of how many wins a player is responsible for on their team. Player efficiency is another metric that represents a rating of a players overall performance, calculated using both positive and negative contributions to their team. Player per attempts to show a players contribution to their team’s success, similar to win shares. Among all variables vorp shares the highest correlation with award_share. VORP stands for Value Over Replacement Player, which is a metric that estimates how much a player contributes to their team, compared to the contribution a hypothetical replacement player would provide.</p>
<p>It is important to note that almost all variables do have correlations with award_share that would be considered weak or moderate (values around 0.10-0.50).</p>
</section>
<section id="visual-eda" class="level3">
<h3 class="anchored" data-anchor-id="visual-eda">Visual EDA</h3>
<section id="points-per-game" class="level4">
<h4 class="anchored" data-anchor-id="points-per-game">Points Per Game</h4>
<p>Now i think most of us would think that the player getting the most buckets is the most likely to win the MVP. After all the main objective is to outscore your opponent, let’s visualize the relationship between points per game and award share using a scatter plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nba, <span class="fu">aes</span>(<span class="at">x =</span> pts_per_g, <span class="at">y =</span> award_share)) <span class="sc">+</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="NBA_MVP_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that the scatter plot is pretty spread out, meaning that maybe scoring the most points isn’t the only metric that matters in MVP voting. Additionally I believe this can be explained as there might be some observations where a player scored a lot of points in a few games and their average was very high but they did not play enough games to be considered for MVP. This graph shows us that points are important, but it is better to look at a player’s total in-game contribution.</p>
</section>
<section id="per-player-efficiency-rating" class="level4">
<h4 class="anchored" data-anchor-id="per-player-efficiency-rating">PER (Player Efficiency Rating)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nba, <span class="fu">aes</span>(<span class="at">x =</span> is_mvp, <span class="at">y =</span> per, <span class="at">fill =</span> mvp_vote)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"gold"</span>)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PER for MVP vs Non-MVP Players"</span>, <span class="at">x =</span> <span class="st">"MVP"</span>, <span class="at">y =</span> <span class="st">"PER"</span>) <span class="sc">+</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="NBA_MVP_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that on average MVPs are ones with very high player efficiency scores, though there is a good amount of observations in the non MVP group that reach the same per scores as the MVP group. This makes sense as we know that there is only one winner and there are also many other players who played well in any given season.</p>
</section>
<section id="vorp" class="level4">
<h4 class="anchored" data-anchor-id="vorp">VORP</h4>
<p>Value over replacement player, as previously mentioned, is a metric that measures how much a player contributes, compared to a hypothetical role player.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nba, <span class="fu">aes</span>(vorp)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> mvp_vote)) <span class="sc">+</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"gold"</span>)) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="NBA_MVP_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that in general, the higher VORP value, the more votes we see for a player in that years MVP voting.</p>
</section>
<section id="win-shares" class="level4">
<h4 class="anchored" data-anchor-id="win-shares">Win Shares</h4>
<p>Win Shares is an advanced basketball statistic that attempts to measure a player’s total contribution to their team’s success, assigning credit for team wins based on individual performance metrics. In the histogram above, we visualize the distribution of Win Shares (<code>ws</code>) for players, with bars colored by whether the player received MVP votes (<code>TRUE</code>&nbsp;in yellow,&nbsp;<code>FALSE</code>&nbsp;in black).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nba, <span class="fu">aes</span>(ws)) <span class="sc">+</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> mvp_vote)) <span class="sc">+</span>   </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"gold"</span>)) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="NBA_MVP_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the plot, we can see that while most players cluster around moderate Win Share values (between 2 and 10), those who received MVP votes tend to have significantly higher values. In particular, MVP vote-getters are concentrated toward the right tail of the distribution, suggesting that higher Win Shares are strongly associated with a greater likelihood of MVP consideration. This indicates Win Shares is likely a meaningful predictor in modeling MVP voting outcomes.</p>
</section>
<section id="box-plus-minus" class="level4">
<h4 class="anchored" data-anchor-id="box-plus-minus">Box Plus Minus</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nba, <span class="fu">aes</span>(<span class="at">x =</span> award_share, <span class="at">y =</span> bpm)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="NBA_MVP_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see a pretty clear relationship between box plus minus and sward share. That is, we observe that among players who received mvp votes, they all had high values of box plus minus, with very few having negative values and a majority of observations that have high award shares being over a box plus minus score of 5. This means that box plus minus will be very helpful in predicting our outcome variable award_share.</p>
</section>
</section>
</section>
<section id="building-the-models" class="level2">
<h2 class="anchored" data-anchor-id="building-the-models">Building the Models</h2>
<p>Now its time to build our models, but first we have to do some preliminary work such as splitting our data and setting up our recipe and workflows.</p>
<section id="model-selection" class="level3">
<h3 class="anchored" data-anchor-id="model-selection">Model Selection</h3>
<p>Now we can choose our final list of variables to be included in the model. Season will not matter and we will simply assume that any specific era does not effect a players chances to win. This may be an issue as different eras often show different trends in in-game stats, anything like claims that more points are scored in the current era as compared to previous eras. Other variables I will not include are ones that measure percentages of baskets. This includes metrics like field goal percentage. We do this since these are metrics are not highly correlated with our outcome and are also correlated with other variables that may capture their contribution better (for example field goal percentage and field goals per game). We will keep all core stats (points, assists, rebounds, turnovers, etc.) and true shooting percentage and drop efg_pct and fg_pct, since ts_pct is the most informative shooting metric. Usage percentage is another variable we will keep as it is unique and not correlated with any other variables. For general player stats we will keep per, ws_per_48 (this is more informative than the regular ws variable), and vorp and remove their specialized versions (ows and dws). Lastly we will remove mov and instead keep mov_adj as it is more informative and keep win_loss_pct and award_share (this one is the most important one). Now that we finalized our variable selection we can get into setting up our recipe</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="200.gif" class="img-fluid quarto-figure quarto-figure-center figure-img" width="494"></p>
</figure>
</div>
<p>Alright chill Bron, we still have a long way to go.</p>
</section>
<section id="splitting-the-data" class="level3">
<h3 class="anchored" data-anchor-id="splitting-the-data">Splitting the Data</h3>
<p>Now we first need to split our data into a training and testing set. We do this to later measure our models performance. Essentially we train it on the training data set and then use the model on the testing data set to see how well our model generalizes on unseen data. We stratify on the outcome variable award_share, we do this to ensure that both the training and testing sets have a similar distribution of award outcomes. This helps prevent any imbalance such as one set having mostly high or low award shares that could lead to misleading model performance or biased results.</p>
<p>We also used a technique called cross validation, specifically k-fold cross validation, to get a more accurate estimate of model performance. In this method, the data is split into k smaller parts (“folds”). The model is trained on k-1 folds and tested on the remaining one. This process is repeated k times so each part gets used as a test set once. The final performance is averaged across all k runs, giving us a more stable estimate than just a single train/test split.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2013</span>) <span class="co"># for replicability</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>nba_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(nba, <span class="at">prop =</span> <span class="fl">0.80</span>, <span class="at">strata =</span> award_share)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>nba_train <span class="ot">&lt;-</span> <span class="fu">training</span>(nba_split)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>nba_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(nba_split)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>nba_folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(nba_train, <span class="at">v =</span> <span class="dv">5</span>, <span class="at">strata =</span> award_share)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="recipe-building" class="level3">
<h3 class="anchored" data-anchor-id="recipe-building">Recipe Building</h3>
<p>In order to train our models we first need to make our recipe for our workflows. Since we are trying to predict x, we use all other variables to do this. We do this using tidymodels which includes a recipe function which we can use to set up our equation.</p>
<p>Our equation will be set up to where we predict the outcome variable award_share calculated as some function using the rest of the variables we chose. We normalize all predictors to have mean 0 and standard deviation 1. All variables are numeric so we do not have to worry about any transformations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># setting up our recipe</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a> nba_recipe <span class="ot">&lt;-</span> nba <span class="sc">%&gt;%</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">recipe</span>(award_share <span class="sc">~</span> gs <span class="sc">+</span> mp_per_g <span class="sc">+</span> fg_per_g <span class="sc">+</span> fga_per_g <span class="sc">+</span> ft_per_g <span class="sc">+</span> fta_per_g <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>             pts_per_g <span class="sc">+</span> trb_per_g <span class="sc">+</span> ast_per_g <span class="sc">+</span> stl_per_g <span class="sc">+</span> blk_per_g <span class="sc">+</span> tov_per_g <span class="sc">+</span> per <span class="sc">+</span>                ws_per_48 <span class="sc">+</span> vorp <span class="sc">+</span> ts_pct <span class="sc">+</span> usg_pct <span class="sc">+</span> mov_adj <span class="sc">+</span> win_loss_pct <span class="sc">+</span> bpm) <span class="sc">%&gt;%</span> </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">step_normalize</span>(<span class="fu">all_predictors</span>()) </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a> <span class="co"># prepping and baking our recipe</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a> <span class="fu">prep</span>(nba_recipe) <span class="sc">%&gt;%</span> </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>   <span class="fu">bake</span>(<span class="at">new_data =</span> nba_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6,235 × 21
         gs mp_per_g fg_per_g fga_per_g ft_per_g fta_per_g pts_per_g trb_per_g
      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1  0.940      1.00     2.45     1.55     1.03      1.31      1.95      1.34  
 2 -0.00437    0.440   -0.232   -0.253    0.642     0.686    -0.105    -1.31  
 3 -1.93      -1.75    -0.777   -0.976   -0.470    -0.202    -0.834    -0.0256
 4  1.05       1.36     1.46     1.41     0.315     0.164     1.03      1.07  
 5 -1.78      -1.37    -0.529   -0.590   -0.470    -0.306    -0.651    -0.0256
 6  0.789      0.611    0.215    0.0124  -0.535    -0.620    -0.123     1.34  
 7 -1.33      -0.894    0.215   -0.0599   0.0536    0.0591    0.0228   -0.784 
 8 -1.82      -1.59    -1.08    -0.879   -0.666    -0.724    -0.998    -1.20  
 9 -0.231      0.491    1.46     1.43     0.250     0.164     1.03     -1.12  
10  0.109     -0.774   -1.12    -1.10    -0.600    -0.672    -1.13     -0.405 
# ℹ 6,225 more rows
# ℹ 13 more variables: ast_per_g &lt;dbl&gt;, stl_per_g &lt;dbl&gt;, blk_per_g &lt;dbl&gt;,
#   tov_per_g &lt;dbl&gt;, per &lt;dbl&gt;, ws_per_48 &lt;dbl&gt;, vorp &lt;dbl&gt;, ts_pct &lt;dbl&gt;,
#   usg_pct &lt;dbl&gt;, mov_adj &lt;dbl&gt;, win_loss_pct &lt;dbl&gt;, bpm &lt;dbl&gt;,
#   award_share &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="methods" class="level3">
<h3 class="anchored" data-anchor-id="methods">Methods</h3>
<p>Since we are doing a predicting a continuous variable we will be using regression methods to predict our outcome.</p>
<p>I will implement 4 models to be explained in the following sections</p>
<p>In general all models will follow the same working steps. We first define the model and it’s type, in this case we will be choosing the mode to be regression. Next we set up a workflow and add our model and recipe we defined earlier. Some models will have parameters which we can tune in order to find the best possible values, we do this by defining a tuning grid with reasonable ranges for the parameters, we can later check which set of parameters performed the best. We then tune the models and specify the workflow, k-fold cross validation folds, and the tuning grid for our chosen parameters to tune. Lastly we collect RMSE values and see which model performed the best</p>
<p>We will choose the best model by looking at the metric rmse, which&nbsp;is a metric that measures the average magnitude of the error between predicted and actual values in a model, calculated as the square root of the average of squared differences. The lower the value, the better the model performs, we usually aim for values close to 0.</p>
<section id="simple-linear-regression" class="level4">
<h4 class="anchored" data-anchor-id="simple-linear-regression">Simple Linear Regression:</h4>
<p>A basic model that fits a straight line to the data by modeling the relationship between one or more features and the outcome as a linear function.</p>
<ul>
<li><strong>No major tuning parameters</strong>, but assumes a linear relationship and can struggle with complex patterns.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2013</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># linear regression </span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>lm_wflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>            <span class="fu">add_model</span>(lm_model) <span class="sc">%&gt;%</span> </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">add_recipe</span>(nba_recipe)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>lm_results <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(lm_wflow, <span class="at">resamples =</span> nba_folds, <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse))</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(lm_results) <span class="sc">%&gt;%</span> </span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  kable</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">std_err</th>
<th style="text-align: left;">.config</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0698402</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0030238</td>
<td style="text-align: left;">Preprocessor1_Model1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We see that simple linear regression gives us an average rmse of 0.0698, very close to 0.07, this is good on it’s own, but let’s compare it to the other models average rmse first</p>
</section>
<section id="k-nearest-neighbors" class="level4">
<h4 class="anchored" data-anchor-id="k-nearest-neighbors">K-Nearest Neighbors:</h4>
<p>Predicts the outcome for a data point by looking at the&nbsp;<em>k</em>&nbsp;closest points in the training set. The prediction is the average (for regression) or most common class (for classification) among those neighbors.</p>
<ul>
<li><strong>neighbors:</strong>&nbsp;Controls how many nearby points influence the prediction. A small neighbors can lead to overfitting, while a large neighbors&nbsp;may smooth out important patterns.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2013</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># k-nearest neighbors</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>kknn_model <span class="ot">&lt;-</span> <span class="fu">nearest_neighbor</span>(<span class="at">neighbors =</span> <span class="fu">tune</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>              <span class="fu">set_engine</span>(<span class="st">"kknn"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>              <span class="fu">set_mode</span>(<span class="st">"regression"</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>kknn_wflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>              <span class="fu">add_model</span>(kknn_model) <span class="sc">%&gt;%</span> </span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>              <span class="fu">add_recipe</span>(nba_recipe)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>neighbors_grid <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(<span class="fu">neighbors</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">20</span>)), <span class="at">levels =</span> <span class="dv">20</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>tune_res_kknn <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">object =</span> kknn_wflow, </span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> nba_folds, </span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> neighbors_grid,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="fu">show_best</span>(tune_res_kknn, <span class="at">metric =</span> <span class="st">"rmse"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 4%">
<col style="width: 13%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">neighbors</th>
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">std_err</th>
<th style="text-align: left;">.config</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">20</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0507618</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0026685</td>
<td style="text-align: left;">Preprocessor1_Model20</td>
</tr>
<tr class="even">
<td style="text-align: right;">19</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0507921</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0026703</td>
<td style="text-align: left;">Preprocessor1_Model19</td>
</tr>
<tr class="odd">
<td style="text-align: right;">18</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0508401</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0026715</td>
<td style="text-align: left;">Preprocessor1_Model18</td>
</tr>
<tr class="even">
<td style="text-align: right;">17</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0509014</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0026685</td>
<td style="text-align: left;">Preprocessor1_Model17</td>
</tr>
<tr class="odd">
<td style="text-align: right;">16</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0509578</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0026519</td>
<td style="text-align: left;">Preprocessor1_Model16</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We see that in general, the k-nearest neighbors model is giving us a mean rmse values around 0.05, which is good and better than our simple linear regression model.</p>
</section>
<section id="elastic-net" class="level4">
<h4 class="anchored" data-anchor-id="elastic-net">Elastic Net</h4>
<p>A linear model that combines Lasso and Ridge regression to improve prediction and handle multicollinearity by penalizing large coefficients.</p>
<ul>
<li><p><strong>Mixture:</strong>&nbsp;Controls the mix between Lasso (<code>alpha = 1</code>) and Ridge (<code>alpha = 0</code>).</p></li>
<li><p><strong>Penalty:</strong> Controls how strongly the model penalizes large coefficients to avoid overfitting.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2013</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>elastic_net <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>(<span class="at">penalty =</span> <span class="fu">tune</span>(), <span class="at">mixture =</span> <span class="fu">tune</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>               <span class="fu">set_engine</span>(<span class="st">"glmnet"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>               <span class="fu">set_mode</span>(<span class="st">"regression"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>elasNet_wflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">add_model</span>(elastic_net) <span class="sc">%&gt;%</span> </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">add_recipe</span>(nba_recipe)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>pandm_grid <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(<span class="fu">penalty</span>(), <span class="fu">mixture</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)), <span class="at">levels =</span> <span class="dv">30</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>tune_res_elas <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">object =</span> elasNet_wflow,</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> nba_folds,</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> pandm_grid,</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="fu">show_best</span>(tune_res_elas, <span class="at">metric =</span> <span class="st">"rmse"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 3%">
<col style="width: 12%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">penalty</th>
<th style="text-align: right;">mixture</th>
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">std_err</th>
<th style="text-align: left;">.config</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.2413793</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0698295</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0030291</td>
<td style="text-align: left;">Preprocessor1_Model211</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.2413793</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0698295</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0030291</td>
<td style="text-align: left;">Preprocessor1_Model212</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.2413793</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0698295</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0030291</td>
<td style="text-align: left;">Preprocessor1_Model213</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.2413793</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0698295</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0030291</td>
<td style="text-align: left;">Preprocessor1_Model214</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.2413793</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0698295</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0030291</td>
<td style="text-align: left;">Preprocessor1_Model215</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We see that in general, Elastic Net also gives us average rmse values near 0.07, which again is not bad, just compared to the result from k-nearest neighbors, this wouldn’t be our first choice when it comes to final model selection</p>
</section>
<section id="random-forest" class="level4">
<h4 class="anchored" data-anchor-id="random-forest">Random Forest</h4>
<p>An ensemble model that builds many decision trees and averages their predictions to reduce overfitting and improve accuracy.</p>
<ul>
<li><p><strong>trees&nbsp;(number of trees):</strong>&nbsp;More trees can improve performance but take longer to train.</p></li>
<li><p><strong>min_n:</strong>&nbsp;Sets the minimum number of samples required at a leaf node, controlling complexity.</p></li>
<li><p><strong>mtry:</strong>&nbsp;Limits the number of features considered when splitting, adding randomness and improving generalization. Since we have 20 predictors, the valid range for this is 1-20</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2013</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># random forest model</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>rf_model <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>(<span class="at">mtry =</span> <span class="fu">tune</span>(), <span class="at">trees =</span> <span class="fu">tune</span>(), <span class="at">min_n =</span> <span class="fu">tune</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">set_engine</span>(<span class="st">"ranger"</span>, <span class="at">importance =</span> <span class="st">"impurity"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">set_mode</span>(<span class="st">"regression"</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>rf_wflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">add_model</span>(rf_model) <span class="sc">%&gt;%</span> </span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>            <span class="fu">add_recipe</span>(nba_recipe)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>rf_params <span class="ot">&lt;-</span> <span class="fu">parameters</span>(</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mtry</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">20</span>) ),  <span class="co"># finalizes mtry based on # of predictors</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">trees</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">200</span>)),  <span class="co"># range for number of trees</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">min_n</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">20</span>))       <span class="co"># minimum samples in a node</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Set levels to 5 for the grid</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>rf_grid <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(rf_params, <span class="at">levels =</span> <span class="dv">5</span>)</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="co"># tuning </span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>tune_rf_res <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">object =</span> rf_wflow, </span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> nba_folds, </span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> rf_grid,</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse)</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a><span class="fu">show_best</span>(tune_rf_res, <span class="at">metric =</span> <span class="st">"rmse"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 3%">
<col style="width: 12%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">mtry</th>
<th style="text-align: right;">trees</th>
<th style="text-align: right;">min_n</th>
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">std_err</th>
<th style="text-align: left;">.config</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0478313</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0025892</td>
<td style="text-align: left;">Preprocessor1_Model032</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">162</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0478909</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0028464</td>
<td style="text-align: left;">Preprocessor1_Model042</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0481218</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0027026</td>
<td style="text-align: left;">Preprocessor1_Model047</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0481529</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0024308</td>
<td style="text-align: left;">Preprocessor1_Model007</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0482630</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0028668</td>
<td style="text-align: left;">Preprocessor1_Model022</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We see that random forest has the lowest mean rmse, score out of all models, around 0.0478. This means that we can choose this model as it performed best on the cross validation data.</p>
</section>
</section>
<section id="results-for-best-model" class="level3">
<h3 class="anchored" data-anchor-id="results-for-best-model">Results for Best Model</h3>
<p>So since random forest performed the best lets now check what parameters it chose to for the best random forest model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>tune_rf_res <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mean) <span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 3%">
<col style="width: 12%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">mtry</th>
<th style="text-align: right;">trees</th>
<th style="text-align: right;">min_n</th>
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">std_err</th>
<th style="text-align: left;">.config</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0478313</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0025892</td>
<td style="text-align: left;">Preprocessor1_Model032</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>So now we see the value for our best random forest model and the parameters it chose. Random Forest #32 with 5 predictors, 87 trees, and a minimal node size of 8 did the best with a mean rmse value of 0.04783. #32 the real MVP</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="kevin-durant-real-mvp.gif" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</section>
<section id="fitting-best-model-to-training-data" class="level3">
<h3 class="anchored" data-anchor-id="fitting-best-model-to-training-data">Fitting best model to training data</h3>
<p>Now that we have our best performing model, lets fit it to the training set</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>best_rf <span class="ot">&lt;-</span> <span class="fu">select_best</span>(tune_rf_res, <span class="at">metric =</span> <span class="st">'rmse'</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>rf_final_wflow <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(rf_wflow, best_rf)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>rf_final_fit <span class="ot">&lt;-</span> <span class="fu">fit</span>(rf_final_wflow, <span class="at">data =</span> nba_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that we fit it to the training data, and effectively trained our model using it, let’s fit it to the testing data and check our results</p>
<section id="testing-the-random-forest-model" class="level4">
<h4 class="anchored" data-anchor-id="testing-the-random-forest-model">Testing the Random Forest Model</h4>
<p>Let’s test out our random forest model on the nba_test data set</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>rf_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(rf_final_fit, <span class="at">new_data =</span> nba_test) </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>nba_test_pred <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(rf_predictions, nba_test)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>nba_test_pred <span class="sc">%&gt;%</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">metrics</span>(<span class="at">truth =</span> award_share, <span class="at">estimate =</span> .pred) <span class="sc">%&gt;%</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.metric <span class="sc">==</span> <span class="st">"rmse"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0497831</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Using our model on the testing data led to an rmse score of 0.05, which is very good!</p>
<p>Lets plot predicted vs actual to see how well it did truly</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>nba_test_pred <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .pred, <span class="at">y =</span> award_share)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">lty =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="NBA_MVP_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Well that doesn’t look too good. We observe that in general, this model performs well for award share values close to 0. Once we start getting to higher award_share values, the model seems to begin to struggle a bit. It performs well in the middle ranged of award_share. This makes sense as the data did contain a lot of 0 values for award share, players who received no vote, so the model might be more inclined to predict closer to 0. This model can definitely be improved but for our purposes, this should do just fine.</p>
<p>We can also check which variables were most important in predicting the outcome and maybe to solidify our belief that advanced metrics are more telling of a player’s MVP contention, and because it’s fun to look at.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>rf_final_fit <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vip</span>(<span class="at">aesthetics =</span> <span class="fu">list</span>(<span class="at">fill =</span> <span class="st">"gold"</span>, <span class="at">color =</span> <span class="st">"black"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="NBA_MVP_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It seems the importance generally follows the results we saw in the correlation matrix, vorp was the most important, with player efficiency rating close behind. What surprised me the most is just how little core player statistics influenced the models predictions.</p>
</section>
</section>
</section>
<section id="predicting-the-2025-nba-mvp" class="level2">
<h2 class="anchored" data-anchor-id="predicting-the-2025-nba-mvp">Predicting the 2025 NBA MVP</h2>
<p>Now that we found the best model and assessed it to make sure it generalizes well on unseen data, lets put it to use. The 2025 season has just recently wrapped up and Shai-Gilgeous Alexander was named the 2025 season MVP. However this year’s award came with some controversy. 3-time winner Nikola Jokic also had an amazing season, he even even had a higher player efficiency rating than SGA. Some argued that Jokic had the better season but in the end the voters decided that SGA was the one who would receive the trophy. Now many people feel like SGA’s award came as a result of voter fatigue, as Jokic had won 3 times in the last 5 years. Let’s put our model to the test and see if we can correctly predict the MVP of this NBA season, SGA,</p>
<p>The data used was pulled from basketball-reference.com and includes 2025 player statistics, including in-game metrics as well as advanced player stats. As for mov_adj and win_loss_pct, these are team stats and were pulled from online resources and pushed into a tibble to later be joined with the other data sets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># game metrics and advanced stats</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>nba_2025 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"/Users/paris/SPRING 25/PSTAT 131/PROJECT/2025_game.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 575 Columns: 32
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): player, team, pos, Player-additional
dbl (27): rank, age, g, gs, mp_per_g, fg_per_g, fga_per_g, fg_pct, fg3_per_g...
lgl  (1): award_share

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>advanced_2025 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"/Users/paris/SPRING 25/PSTAT 131/PROJECT/2025_advanced.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 569 Columns: 30
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): player, Team, Pos, Player-additional
dbl (25): Rk, age, G, GS, MP, per, ts_pct, 3PAr, FTr, ORB%, DRB%, TRB%, AST%...
lgl  (1): award_share

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># team stats (mov_adj and win_loss_pct)</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>nba_2025_stats <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>team, <span class="sc">~</span>mov_adj, <span class="sc">~</span>win_loss_pct,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"OKC"</span>,     <span class="fl">12.2</span>, <span class="fl">0.808</span>,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CLE"</span>,      <span class="fl">9.7</span>, <span class="fl">0.758</span>,</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"BOS"</span>,      <span class="fl">8.7</span>, <span class="fl">0.720</span>,</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"IND"</span>,      <span class="fl">2.5</span>, <span class="fl">0.630</span>,</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"HOU"</span>,      <span class="fl">4.2</span>, <span class="fl">0.619</span>,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"NYK"</span>,      <span class="fl">3.4</span>, <span class="fl">0.610</span>,</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"MIN"</span>,      <span class="fl">4.6</span>, <span class="fl">0.598</span>,</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"LAC"</span>,      <span class="fl">4.3</span>, <span class="fl">0.596</span>,</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"DEN"</span>,      <span class="fl">2.6</span>, <span class="fl">0.594</span>,</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"LAL"</span>,      <span class="fl">0.7</span>, <span class="fl">0.586</span>,</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"GSW"</span>,      <span class="fl">2.5</span>, <span class="fl">0.568</span>,</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"MIL"</span>,      <span class="fl">2.1</span>, <span class="fl">0.568</span>,</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"MEM"</span>,      <span class="fl">3.7</span>, <span class="fl">0.557</span>,</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"DET"</span>,      <span class="fl">1.7</span>, <span class="fl">0.523</span>,</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ORL"</span>,     <span class="sc">-</span><span class="fl">0.6</span>, <span class="fl">0.489</span>,</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"SAC"</span>,      <span class="fl">0.3</span>, <span class="fl">0.488</span>,</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"DAL"</span>,     <span class="sc">-</span><span class="fl">1.2</span>, <span class="fl">0.476</span>,</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ATL"</span>,     <span class="sc">-</span><span class="fl">1.5</span>, <span class="fl">0.476</span>,</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CHI"</span>,     <span class="sc">-</span><span class="fl">1.8</span>, <span class="fl">0.470</span>,</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>  <span class="st">"MIA"</span>,     <span class="sc">-</span><span class="fl">0.5</span>, <span class="fl">0.443</span>,</span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a>  <span class="st">"POR"</span>,     <span class="sc">-</span><span class="fl">3.0</span>, <span class="fl">0.439</span>,</span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>  <span class="st">"PHX"</span>,     <span class="sc">-</span><span class="fl">3.0</span>, <span class="fl">0.439</span>,</span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>  <span class="st">"SAS"</span>,     <span class="sc">-</span><span class="fl">2.8</span>, <span class="fl">0.415</span>,</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a>  <span class="st">"TOR"</span>,     <span class="sc">-</span><span class="fl">4.3</span>, <span class="fl">0.366</span>,</span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>  <span class="st">"BKN"</span>,     <span class="sc">-</span><span class="fl">7.1</span>, <span class="fl">0.317</span>,</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a>  <span class="st">"PHI"</span>,     <span class="sc">-</span><span class="fl">6.2</span>, <span class="fl">0.293</span>,</span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a>  <span class="st">"NOP"</span>,     <span class="sc">-</span><span class="fl">9.4</span>, <span class="fl">0.256</span>,</span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a>  <span class="st">"CHA"</span>,     <span class="sc">-</span><span class="fl">9.3</span>, <span class="fl">0.230</span>,</span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a>  <span class="st">"WAS"</span>,    <span class="sc">-</span><span class="fl">12.4</span>, <span class="fl">0.220</span>,</span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a>  <span class="st">"UTA"</span>,     <span class="sc">-</span><span class="fl">9.3</span>, <span class="fl">0.207</span></span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a><span class="co"># merge all datasets (game + advanced + team stats)</span></span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-40"><a href="#cb34-40" aria-hidden="true" tabindex="-1"></a>joined_table <span class="ot">&lt;-</span> nba_2025 <span class="sc">%&gt;%</span></span>
<span id="cb34-41"><a href="#cb34-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(advanced_2025, <span class="at">by =</span> <span class="st">"player"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-42"><a href="#cb34-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(nba_2025_stats, <span class="at">by =</span> <span class="st">"team"</span>)</span>
<span id="cb34-43"><a href="#cb34-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-44"><a href="#cb34-44" aria-hidden="true" tabindex="-1"></a><span class="co"># using same columns as in recipe</span></span>
<span id="cb34-45"><a href="#cb34-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-46"><a href="#cb34-46" aria-hidden="true" tabindex="-1"></a>joined_table <span class="ot">&lt;-</span> joined_table <span class="sc">%&gt;%</span></span>
<span id="cb34-47"><a href="#cb34-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(player,</span>
<span id="cb34-48"><a href="#cb34-48" aria-hidden="true" tabindex="-1"></a>    gs, mp_per_g, fg_per_g, fga_per_g, ft_per_g, fta_per_g,</span>
<span id="cb34-49"><a href="#cb34-49" aria-hidden="true" tabindex="-1"></a>    pts_per_g, trb_per_g, ast_per_g, stl_per_g, blk_per_g, tov_per_g,</span>
<span id="cb34-50"><a href="#cb34-50" aria-hidden="true" tabindex="-1"></a>    per, ws_per_48, vorp, ts_pct, usg_pct, mov_adj, win_loss_pct, bpm</span>
<span id="cb34-51"><a href="#cb34-51" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb34-52"><a href="#cb34-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-53"><a href="#cb34-53" aria-hidden="true" tabindex="-1"></a><span class="co"># clear any mising values</span></span>
<span id="cb34-54"><a href="#cb34-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-55"><a href="#cb34-55" aria-hidden="true" tabindex="-1"></a>joined_table <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(joined_table)</span>
<span id="cb34-56"><a href="#cb34-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-57"><a href="#cb34-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-58"><a href="#cb34-58" aria-hidden="true" tabindex="-1"></a><span class="co"># predictions, predictions table sorted by .pred</span></span>
<span id="cb34-59"><a href="#cb34-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-60"><a href="#cb34-60" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(rf_final_fit, <span class="at">new_data =</span> joined_table) <span class="sc">%&gt;%</span> </span>
<span id="cb34-61"><a href="#cb34-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(player, .pred) <span class="sc">%&gt;%</span> </span>
<span id="cb34-62"><a href="#cb34-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="at">by_group =</span> <span class="fu">desc</span>(.pred)) <span class="sc">%&gt;%</span> </span>
<span id="cb34-63"><a href="#cb34-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb34-64"><a href="#cb34-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">player</th>
<th style="text-align: right;">.pred</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Shai Gilgeous-Alexander</td>
<td style="text-align: right;">0.8876556</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nikola Joki?</td>
<td style="text-align: right;">0.7774955</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Giannis Antetokounmpo</td>
<td style="text-align: right;">0.4397301</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alondes Williams</td>
<td style="text-align: right;">0.3550833</td>
</tr>
<tr class="odd">
<td style="text-align: left;">James Wiseman</td>
<td style="text-align: right;">0.1996443</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jayson Tatum</td>
<td style="text-align: right;">0.1406513</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>And your NBA 2025 Random Forest MVP is, Shai-Gilgeous Alexander!!</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="shai-gilgeous-alexander-shai.gif" class="img-fluid quarto-figure quarto-figure-center figure-img" width="447"></p>
</figure>
</div>
<p>Hold on though, I wouldnt take this model to Vegas just yet. While this result is reflective of the result in real life, it is important to note that unfortunately the resulting table does show some problems in our model, notably how Alondes Williams and James Wiseman are being considered serious MVP candidates. Without going into too much detail on the players, these are both guys who rarely see playing time and in reality are not MVP contenders, however they must have really high scores for some variables (James Wiseman has a free throw percentage of 100% this season), that may have led our model to believe that these might have been serious contenders.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Now after fitting all of our models and seeing our results, we came away with random forest being the best for the job. This makes sense as random forest does well in handling data that may not meet assumptions for other regression models, that is to say it is more flexible to data. However as we see the model still has it’s problems, notably in handling players with inflated stats that may not be representative of their true skill and value on the court.</p>
<p>Our worst models were simple linear regression and elastic net. This also makes sense especially for simple linear regression, as it primarily works best on data that have strong linear relationships, and as we saw, NBA metrics may not have well defined linear relationships with award share.</p>
<p>Now improvement is always good, it is how rookies eventually become MVP. We notice that our model tends to predict closer to 0. This came as a result of the overwhelming amount of 0 values for award share. Stratifying may have helped a little bit but still our model favored predictions closer to 0 a good amount of the time, as seen in the predicted vs actual plot for the random forest model. We may be able to address this by reducing our data size even more, maybe to only include players who received a vote.</p>
<p>We saw that advanced player statistics were among the most important when it came to predicting award shares, and that in-game metrics such as points and rebounds, played little effect. This makes sense as these metrics were designed for cases like this, to determine who is the best player mathematically using very complex formulas for calculations.</p>
<p>And while our model did in the end predict the MVP correctly, it is still important to note its shortcomings and how in the end, the machine may not be able to truly capture everything that goes into an MVP race. There is still a lot more that goes into voting, metrics beyond just basketball, maybe if we had access to these kinds of statistics we could make our model even better.</p>
<p>Yet this process was very fun for me as I got to apply my new machine learning knowledge to something I enjoy. This project helped me learn more about the NBA and sports analytics in general. Thanks for taking the time to read about my project, you the real MVP</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="957bec3b1f1a1effbea313a030d6b0ef.gif" class="img-fluid quarto-figure quarto-figure-center figure-img" width="512"></p>
</figure>
</div>
</section>
<section id="sources" class="level2">
<h2 class="anchored" data-anchor-id="sources">Sources</h2>
<ul>
<li><p>NBA data set was downloaded from Kaggle titled “<a href="https://www.kaggle.com/datasets/robertsunderhaft/nba-player-season-statistics-with-mvp-win-share/data"><strong>1982-2022 “NBA Player Statistics with MVP Votes</strong></a><strong>’</strong>. All data was web scraped from basketball-reference.com by user Robert Sunderhaft.</p></li>
<li><p>nba_2025 was scraped from <a href="https://www.basketball-reference.com/leagues/NBA_2025_advanced.html">basketball-reference.com</a></p></li>
<li><p>mov_adj and win_loss_pct were pulled from <a href="https://www.basketball-reference.com/leagues/NBA_2025_advanced.html">basketball-reference.com</a></p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>